### PR TITLE
Fix all implicit case fallthrough (#287)

### LINKED ISSUE #287: Fix all case fallthrough
1. Annotate all cases which falls through with whatever GCC has decided is the latest for C. 
2. Enable the fall through checks in compilation.

### PR DESCRIPTION
**Pull request by rampageservices**
## Summary

- Enable `-Wimplicit-fallthrough` in `CMakeLists.txt` compiler flags
- Annotate all intentional case fallthroughs with C23 `[[fallthrough]];` attribute

## Changes

| File | Location | Fallthrough |
|------|----------|-------------|
| `src/amacro.c` | `case '0':` → `case '1':` | Comment is conditionally consumed, otherwise falls through to digit parsing |
| `src/callbacks.c` | `SAVE_FILE_RS274XM` → `SAVE_FILE_DRILL` | Merged visible layers export shares drill export path |
| `src/callbacks.c` | `LAYER_SELECTED` → `default` | Resolves selected index then falls to default toggle logic |
| `src/csv.c` (×2) | `ST_START` → `ST_COLLECT` | State-machine transition (char and wchar_t variants) |
| `src/drill.c` | `case 'R':` → `case 'S':` | Repeat-hole command falls through to spindle speed handler |
| `src/main.c` | `case 'w':` → `case 'W':` | Lowercase sets pixel flag then shares window-size parsing |

## Test plan

- [x] Clean build with zero `-Wimplicit-fallthrough` warnings
- [x] 94/104 regression tests pass (same 10 pre-existing rendering mismatches)
- [x] Functional test: `test-amacro-hex-expression.gbx` exports correctly
- [x] Functional test: `test-gerber-x2-attributes.gbx` exports correctly

Closes #287

### CODE REVIEW

File: src/drill.c [hunk 1]
```diff
@@ -873,6 +873,7 @@ parse_drillfile(gerb_file_t *fd, gerbv_HID_Attribute *attr_list, int n_attr, int
 	      }
 	      
 	    }
+	    [[fallthrough]];
```
Comment (spe-ciellt) [inline src/drill.c]: This is probably a bug and should be a `break`.  Remove the `[[fallthrough]]` line and replace the empty line with `break;`.

**Review by spe-ciellt — CHANGES_REQUESTED** [review]
One old bug found, but was fixed in the wrong way.

**Comment by spe-ciellt** [comment]
### Hard blocker — `drill.c` `case 'R'` → `case 'S'`

After processing a repeat-hole `R` command in the body section, the code falls through into `case 'S'` (spindle speed), which logs a spurious note and calls `eat_line(fd)` — consuming the **next line** from the drill file. That next line is typically a coordinate, tool change, or `M30` end-of-file command, which gets silently discarded.

```c
case 'R':
    if (state->curr_section == DRILL_HEADER) {
        // log error
    } else {
        // parse repeat count and step values
        // emit rcnt drill holes
    }
    // [[fallthrough]]; <-- PR annotates this as intentional
case 'S':
    gerbv_stats_printf(..., _("Ignoring setting spindle speed..."));
    eat_line(fd);
    break;
```

The existing golden-image test passes because it was generated against the same buggy code. The correct fix is a `break;` before `case 'S':`, not a `[[fallthrough]];`.

---

### Likely bug — `callbacks.c` RS274XM → DRILL

On the success path for `CALLBACKS_SAVE_FILE_RS274XM`, the code falls through into the `CALLBACKS_SAVE_FILE_DRILL` block which overwrites `windowTitle` (leaking the RS-274X string) with a drill-file dialog title and sets the file extension to `.drl`. An RS-274X merge export should not be presenting a drill-file dialog. This looks like a missing `break;` that has always been there, with the PR locking it in as intentional.

---

### Correct annotations (6 of 8)

| Location | Assessment |
|---|---|
| `amacro.c` — `case '0'` → `case '1'` | Correct — `'0'` mid-expression is a digit |
| `callbacks.c` — `LAYER_SELECTED` → `default` | Correct — replaces `/* No break */` which didn't match GCC's regex |
| `csv.c` (×2) — `ST_START` → `ST_COLLECT` | Correct — standard state machine optimization |
| `main.c` — `case 'w'` → `case 'W'` | Correct — intentional shared getopt handling |

The three existing `/* fall through */` comments in `scheme.c` are correctly left untouched — GCC level 3 already accepts them.

**When you fixed it**, amend it into current commit and push it `--force--with-lease`.

**Comment by rampageservices** [comment]
Fixed both — `drill.c` case 'R' and `callbacks.c` RS274XM now have `break;` instead of `[[fallthrough]];`. Force-pushed the amended commit.

File: src/drill.c (hunk 1 above)
Comment (rampageservices) [reply src/drill.c]: This is now a proper break; (see below)
